language: node_js
node_js:
- '6'
sudo: false
addons:
  sauce_connect:
    username: metal-router
    no_ssl_bump_domains: all
  jwt:
    secure: fUwXX7NEHN9vNVaE7kCsZxGu2UCxyWcgZwcszpwcbl3dxrAMM6TjQPUb41sTIUqCnzp/gHdE42aS/HMBj09pGkKYb3THJut2nNrDv4UI/fkVTM6GOXW2/oCZv10rhukd1S5FYocN4WgbJHGEbPVdAoUyAKW4ZH7o8sfeR29wmz5VzQA/cOCGjIY8EH5SGyXdoiOCx5JDypYox1HDcNpFSw37dZfZNqk+S1vUem/N87oZPYZ/AMaHt1gOYVye2wLyUlGoou6Wlki668cvT+I5lMkbg4GL6kHwTsLyCWTQF1NTXkH91fR6EzSSOdm+xA97DoSNqWRC7OP7ExVZg6R+wn+vnmCm33FXg/xG+0aY3ProiqaRzN85xKCUGUQqagDcCIEhTzpJf5xdN18HL9Lrqmuwd+1FWw7HRdctzIdHopcrpBVW53epjZzLorLiqAgHH2Toho1hIhvclOLF9cWUZp6yzh8j/j61Yp8M7lB+VCX9vkoKfI3aZf9GjztSf2CsThEqeDWN6VQHrvXe5WWl+36/QCQu33C47UkdIT7ELbavSjEbtgAI3sJv58MvXjMFADPBLJcpZLk6NSsFCQcxcoPIFyd8NVeuevF8Mid1h1gwtKJirQFs2E76PhfOUsbDdPz4JnvZsCiOp0tPdurTXX1GdghZZLG2e7Lc8H6j99I=
before_install:
- npm install -g gulp
- npm install
- gulp build
script: gulp test:saucelabs
